/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.newgame2023;
 
/**
 *
 * @author USER
 */
public class Round extends javax.swing.JFrame {
 
   int attempt=1;
    int round=1;
   int count=0;
     public Round() {
        initComponents();
        range.setText("01 to 10");
        r.setText(String.valueOf(round));
        Remaining.setText(String.valueOf(3-attempt));
     }
    
    public int random(int max,int min){
      int ran=(int)(Math.random()*(max-min+1)+min);
       OF.setText(String.valueOf(ran));  
       return ran;
    }
    public void func(String a){
        
        if(attempt==1){
             int ran=random(1,10);
             
             validation(ran);
        }
        else if(attempt==2){
             int ran=random(11,20);
             
             validation(ran);
        }
         else if(attempt==3){
             int ran=random(21,30);
             
             validation(ran);
        }
                      
        } 
    public void validation(int ran){
        int val=Integer.parseInt(A.getText());
        if(ran==val){
            count++;
            resu.setText("Matched");
            resu.setForeground(new java.awt.Color(2,255,2));
        }
        else{
            resu.setText("Not Matched");
            resu.setForeground(new java.awt.Color(255,2,2));
        }
    }
       
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        A = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        OF = new javax.swing.JTextField();
        hit = new javax.swing.JButton();
        AtemptL = new javax.swing.JLabel();
        Remaining = new javax.swing.JLabel();
        NextB = new javax.swing.JButton();
        resu = new javax.swing.JLabel();
        r = new javax.swing.JLabel();
        range = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Rounds");
        setBackground(new java.awt.Color(255, 204, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI Historic", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 51));
        jLabel1.setText("Round");
        jLabel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.S_RESIZE_CURSOR));

        jLabel2.setFont(new java.awt.Font("Sitka Small", 3, 18)); // NOI18N
        jLabel2.setText("Enter your Assumption");

        A.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Sitka Small", 3, 18)); // NOI18N
        jLabel3.setText("Actual output");

        OF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OFActionPerformed(evt);
            }
        });

        hit.setBackground(new java.awt.Color(102, 102, 255));
        hit.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        hit.setText("HIT");
        hit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitActionPerformed(evt);
            }
        });

        AtemptL.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        AtemptL.setForeground(new java.awt.Color(102, 0, 255));
        AtemptL.setText("Attempt Remaining :");
        AtemptL.setToolTipText("");
        AtemptL.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        AtemptL.setCursor(new java.awt.Cursor(java.awt.Cursor.NW_RESIZE_CURSOR));
        AtemptL.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);

        Remaining.setFont(new java.awt.Font("Modern No. 20", 3, 14)); // NOI18N
        Remaining.setForeground(new java.awt.Color(51, 51, 51));

        NextB.setBackground(new java.awt.Color(255, 0, 0));
        NextB.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        NextB.setText("Next Attempt");
        NextB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextBActionPerformed(evt);
            }
        });

        r.setFont(new java.awt.Font("Modern No. 20", 3, 14)); // NOI18N
        r.setForeground(new java.awt.Color(51, 51, 51));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 255));
        jLabel4.setText("Please Type in range");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(16, 16, 16)
                                        .addComponent(jLabel3))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(21, 21, 21))
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(r, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(OF, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(A, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(range, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(34, 34, 34)
                                        .addComponent(hit, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                                        .addComponent(resu, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(AtemptL)
                        .addGap(42, 42, 42)
                        .addComponent(Remaining, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(9, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(191, 191, 191)
                .addComponent(NextB)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(r, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(A, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(range, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(OF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3))
                    .addComponent(resu, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Remaining, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AtemptL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(NextB)
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_AActionPerformed

    private void OFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OFActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_OFActionPerformed

    private void hitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitActionPerformed
        // TODO add your handling code here:
            String ans= A.getText();
            func(ans);  
    }//GEN-LAST:event_hitActionPerformed

    private void NextBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextBActionPerformed
        // TODO add your handling code here:
      
             if(attempt>=3){
                 round++; 
                 attempt=1;
                 if(round>=3){
                 Result df=new Result();
                 this.setVisible(false);
                 df.setVisible(true);
                 df.Instance.lb1.setText(String.valueOf(count));
                 df.lb1.setForeground(new java.awt.Color(2,155,120));
                 if(count>=6) {
                     df.Instance.lb2.setText("WOW !! EXCELLENT");
                     df.lb2.setForeground(new java.awt.Color(255,2,2));
                 }
                 else if(count>=3 && count<5){
                     df.Instance.lb2.setText("GOOD");
                     df.lb2.setForeground(new java.awt.Color(2,255,2));
                 }
                 else if(count<3 && count>=1){
                      df.Instance.lb2.setText("AVERAGE");
                     df.lb2.setForeground(new java.awt.Color(200,125,2));
                 }
                 else{
                     df.Instance.lb2.setText("BAD !!  POOR");
                     df.lb2.setForeground(new java.awt.Color(2,25,200));
                 }
            }
           } 
             
            else{
            attempt++;
            }
            if(attempt==1) range.setText("01 to 10");
            if(attempt==2)
            range.setText("11 to 20");
            if(attempt==3)
            range.setText("21 to 30");
            
            
            Remaining.setText(String.valueOf(3-attempt));
            r.setText(String.valueOf(round));
            A.setText("");
            OF.setText("");
            resu.setText(""); 
            
    }//GEN-LAST:event_NextBActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField A;
    private javax.swing.JLabel AtemptL;
    private javax.swing.JButton NextB;
    private javax.swing.JTextField OF;
    private javax.swing.JLabel Remaining;
    private javax.swing.JButton hit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel r;
    private javax.swing.JLabel range;
    private javax.swing.JLabel resu;
    // End of variables declaration//GEN-END:variables

    private void setVisibble(boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
